"""CONFIGURATION"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""PREFLIGHT CHECKS"""
include: os.path.join("rules", "preflight.smk")

"""Rules"""
include: os.path.join("rules", "illumina.smk")

# Target rules
targets = []
targets.append(expand(os.path.join(dir_fastp,"{sample}_R1.fastq.gz"), sample=sample_names)),
targets.append(expand(os.path.join(dir_fastp,"{sample}_R2.fastq.gz"), sample=sample_names))
targets.append(expand(os.path.join(dir_megahit, "{sample}-pr", "final.contigs.fa"), sample=sample_names)),
targets.append(expand(os.path.join(dir_megahit, "{sample}-pr", "final.gfa"), sample=sample_names)),


rule all:
    input:
        targets
