import yaml
import os
import glob

"""CONFIGURATION"""
configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

"""PREFLIGHT CHECKS"""
include: os.path.join("rules", "0.preflight.smk")

"""Rules"""
include: os.path.join("rules", "1.fastp.smk")
include: os.path.join("rules", "2.hybracter.smk")
include: os.path.join("rules", "2.megahit.smk")
include: os.path.join("rules", "3.bakta.smk")
include: os.path.join("rules", "4.amrfinder.smk")
include: os.path.join("rules", "4.phispy.smk")
include: os.path.join("rules", "5.defensefinder.smk")
include: os.path.join("rules", "6.summary.smk") 
#include: os.path.join("rules", "7.panaroo.smk")

"""TARGETS"""
include: os.path.join("rules", "99.targets.smk")

rule all:
    input:
        targets['asan'],
        targets['pan']

rule asan:
    input:
        targets['asan']

rule pan:
    input:
        targets['pan']
