# Namespaced config file example
sphaehost:
    args: # Command line args will be (over)written here at runtime
        input:
        output:
        db_dir:
        temp_dir:
        sequencing:
    # Add customisable config here
