name: Publish Baczy to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Needed for Trusted Publishing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build Baczy Package
        run: python -m build

      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: baczy-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
